resources:
  - ../../base
  - postgres-db.yaml
  - resource-limits.yaml

patchesStrategicMerge:
  - eso-secret.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            tolerations:
              - key: "environment"
                operator: "Equal"
                value: "ephemeral"
                effect: "NoSchedule"
            nodeSelector:
              environment: "ephemeral"
