apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fleet-backend-secrets-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: fleet-backend-secrets
  dataFrom:
  - extract:
      key: dev-fleet-app-secrets