apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token-external-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: github-token-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: dev-github-token
        property: token
