resources:
  - ../../base

images:
  - name: 873593444498.dkr.ecr.eu-central-1.amazonaws.com/dev-fleet-ecr-backend
    newName: 873593444498.dkr.ecr.eu-central-1.amazonaws.com/prod-fleet-ecr-backend
    newTag: IMAGE_TAG  # Must be set by CI/CD pipeline to a specific release version
  - name: 873593444498.dkr.ecr.eu-central-1.amazonaws.com/dev-fleet-ecr-frontend
    newName: 873593444498.dkr.ecr.eu-central-1.amazonaws.com/prod-fleet-ecr-frontend
    newTag: IMAGE_TAG  # Must be set by CI/CD pipeline to a specific release version

patches:
  - target:
      kind: Ingress
      name: fleet-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: chorogra.me
      - op: replace
        path: /spec/tls/0/hosts/0
        value: chorogra.me
      - op: replace
        path: /spec/tls/0/secretName
        value: fleet-tls-cert-prod
  - target:
      kind: ExternalSecret
      name: fleet-backend-secrets-es
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: prod-fleet-app-secrets
